# Expenditure endpoints



### List Expenditures 
GET http://localhost:3000/auditing

### Create Expenditures 
POST http://localhost:3000/expenditures
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNThiY2VlYi00MDQxLTRhNTAtYjIwNC04NWNhYTJhZDZjMjAiLCJlbWFpbCI6ImpvaG5kb2UxQGdtYWlsLmNvbSIsImlhdCI6MTc0MDk1MzI1OCwiZXhwIjoxNzQwOTU2ODU4fQ.oz7tkfwdWONKH1KoavTK6XlosxA0NG-T31W7VyjV0Ns

{
    "name": "Legion Tower 7i Gen 8 (Intel) Gaming Desktop",
    "amount": 2099.99,
    "date": "2024-12-31"
}

### List Expenditures 
GET http://localhost:3000/expenditures
Authorization: GciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNThiY2VlYi00MDQxLTRhNTAtYjIwNC04NWNhYTJhZDZjMjAiLCJlbWFpbCI6ImpvaG5kb2UxQGdtYWlsLmNvbSIsImlhdCI6MTc0MDk1MzI1OCwiZXhwIjoxNzQwOTU2ODU4fQ.oz7tkfwdWONKH1KoavTK6XlosxA0NG-T31W7VyjV0Ns

### Read Expenditure
GET http://localhost:3000/expenditures/1c93e5ea-d72a-4b29-a89a-d8fd75283c16
# GET http://localhost:3000/expenditures/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNThiY2VlYi00MDQxLTRhNTAtYjIwNC04NWNhYTJhZDZjMjAiLCJlbWFpbCI6ImpvaG5kb2UxQGdtYWlsLmNvbSIsImlhdCI6MTc0MDk1MzI1OCwiZXhwIjoxNzQwOTU2ODU4fQ.oz7tkfwdWONKH1KoavTK6XlosxA0NG-T31W7VyjV0Ns

### Update Expenditure
PUT http://localhost:3000/expenditures/1c93e5ea-d72a-4b29-a89a-d8fd75283c16
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNThiY2VlYi00MDQxLTRhNTAtYjIwNC04NWNhYTJhZDZjMjAiLCJlbWFpbCI6ImpvaG5kb2UxQGdtYWlsLmNvbSIsImlhdCI6MTc0MDk1MzI1OCwiZXhwIjoxNzQwOTU2ODU4fQ.oz7tkfwdWONKH1KoavTK6XlosxA0NG-T31W7VyjV0Ns

{
    "name": "Legion Tower 7i Gen 8 (Intel) Gaming Desktop",
    "amount": 2099.99,
    "date": "2024-12-31"
}

### Delete Expenditure
DELETE http://localhost:3000/expenditures/1c93e5ea-d72a-4b29-a89a-d8fd75283c16
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNThiY2VlYi00MDQxLTRhNTAtYjIwNC04NWNhYTJhZDZjMjAiLCJlbWFpbCI6ImpvaG5kb2UxQGdtYWlsLmNvbSIsImlhdCI6MTc0MDk1MzI1OCwiZXhwIjoxNzQwOTU2ODU4fQ.oz7tkfwdWONKH1KoavTK6XlosxA0NG-T31W7VyjV0Ns



# User


### Sign up
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "johndoe2@gmail.com",
    "password": "JohnPwd_12"
}

### Log in
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "johndoe1@gmail.com",
    "password": "JohnPwd12_"
}


###
GET http://localhost:3000/