# Expenditure endpoints

### Create Expenditures 
POST http://localhost:3000/expenditures
Content-Type: application/json

{
    "name": "Legion Tower 7i Gen 8 (Intel) Gaming Desktop",
    "amount": 2099.99,
    "date": "2024-31-12"
}

### List Expenditures 
GET http://localhost:3000/expenditures
Authorization: am9obmRvZUBnbWFpbC5jb206ZGVjZWM2OTQtNmQ5Ny00MTk5LTg1NDQtZjRiYmU3ZWE3NTNi

### Read Expenditure
GET http://localhost:3000/expenditures/1

### Update Expenditure
PUT http://localhost:3000/expenditures/11
Content-Type: application/json

{
    "name": "MacBook pro laptop",
    "amount": 5099.99,
    "date": "2025-01-01"
}

### Delete Expenditure
DELETE http://localhost:3000/expenditures/0


# User


### Sign up
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "johndoe1@gmail.com",
    "password": "JohnPwd12_"
}

### Log in
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "JohnPwd12_"
}