# Expenditure endpoints

### Create Expenditures 
POST http://localhost:3000/expenditures
Content-Type: application/json

{
    "name": "Legion Tower 7i Gen 8 (Intel) Gaming Desktop",
    "amount": 2099.99,
    "date": "2024-31-12"
}

### List Expenditures 
GET http://localhost:3000/expenditures?

### Read Expenditure
GET http://localhost:3000/expenditures/1

### Update Expenditure
PUT http://localhost:3000/expenditures/11
Content-Type: application/json

{
    "name": "MacBook pro laptop",
    "amount": 5099.99,
    "date": "2025-01-01"
}

### Delete Expenditure
DELETE http://localhost:3000/expenditures/0

